run01-pipe:
	gcc ativ01-pipe.c -o ativ
	./ativ "O macaco(filme) é muito estranho"

run01-fifo-receive:
	gcc ativ01-fifo-receive.c -o ativ-receive
	./ativ-receive

run01-fifo-send:
	gcc ativ01-fifo-send.c -o ativ-send
	./ativ-send

run02:
	gcc ativ02.c -o ativ
	./ativ

run03:
	gcc ativ03.c utils/utils.c -o ativ
	./ativ

run04-client:
	gcc ativ04-client.c -o ativ-client
	./ativ-client

run04-server:
	gcc ativ04-server.c -o ativ-server
	./ativ-server

clean:
	rm -rfd ativ-* ativ log.txt result.txt