run01-pipe:
	gcc ativ01-pipe.c -o ativ
	./ativ "O macaco(filme) é muito estranho"

run01-fifo-receive:
	gcc ativ01-fifo-receive.c -o ativ-receive
	./ativ-receive

run01-fifo-send:
	gcc ativ01-fifo-send.c -o ativ-send
	./ativ-send

run02:
	gcc ativ02.c -o ativ
	./ativ

clean:
	rm -rfd ativ-* ativ log.txt