run01:
	gcc ativ01.c -o ativ
	./ativ 3

run02:
	gcc ativ02.c -o ativ
	./ativ ping 8.8.8.8 -c 3

run03:
	gcc ativ03.c -o ativ
	./ativ 5 3
	./ativ 5 101

run04:
	gcc ativ04.c -o ativ
	./ativ

clean:
	rm -rfd ativ